

CREATE_LOGS_TABLE = """
CREATE TABLE IF NOT EXISTS logs (
id INTEGER PRIMARY KEY,
date TEXT NOT NULL UNIQUE,
sympt_num INTEGER NOT NULL,
notes TEXT
)
"""


CREATE_LOG_DETAILS_TABLE = """
CREATE TABLE IF NOT EXISTS log_details (
id INTEGER PRIMARY KEY,
logs_id INTEGER NOT NULL,
symptom TEXT NOT NULL,
level TEXT NOT NULL,
FOREIGN KEY (logs_id) REFERENCES logs(id) ON DELETE CASCADE
)
"""


CREATE_USER_PREFERENCES_TABLE = """
CREATE TABLE IF NOT EXISTS user_preferences (
id INTEGER PRIMARY KEY,
language TEXT NOT NULL,
theme TEXT NOT NULL
)
"""


CREATE_SYMPTOMS_TABLE = """
CREATE TABLE IF NOT EXISTS symptoms (
id INTEGER PRIMARY KEY,
symptom TEXT NOT NULL,
track_type TEXT NOT NULL
)
"""